name: "Build & Release"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          version: '3.29.3'
          channel: 'stable'
          cache: false
      - name: 'Checkout Flutter 3.29.3'
        shell: bash
        run: |
          cd $FLUTTER_ROOT
          git fetch --tags
          git checkout 3.29.3
          flutter --version
          cd -
      - run: flutter --version
      - run: flutter pub get

      - name: Decode and Save Keystore
        run: echo "${{ secrets.APP_KEY }}" | base64 -d > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - run: flutter build apk --release

      - name: Save Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          version: '3.29.3'
          channel: 'stable'

      - name: Download sqlite.dll
        run: |
          Invoke-WebRequest -Uri "https://www.sqlite.org/2025/sqlite-dll-win-x64-3500100.zip" -OutFile "sqlite.zip"
          Expand-Archive -Path sqlite.zip -DestinationPath .
          Move-Item -Path .\sqlite3.dll -Destination .\windows\runner\Debug\sqlite3.dll

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows

      - name: Zip Windows Build
        run: |
          $outputPath = "build/windows/runner/Release"
          Compress-Archive -Path "$outputPath/*" -DestinationPath "bonodnd-windows.zip"

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: bonodnd-windows.zip


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk

      - name: Extract version from version.dart
        id: get_version
        run: |
          VERSION=$(grep 'const String appVersion' lib/configs/version.dart | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+)";/\1/')
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Rename APK
        run: mv app-release.apk BonoDND-${{ env.version }}.apk

      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-windows

      - name: Rename Windows ZIP
        run: mv bonodnd-windows.zip BonoDND-${{ env.version }}-windows.zip

      - name: Push APK and Windows ZIP to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            BonoDND-${{ env.version }}.apk
            BonoDND-${{ env.version }}-windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.version }}